# Generated by Django 4.1.1 on 2022-09-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.CharField(choices=[('Monitor1', 'Monitor1'), ('Monitor2', 'Monitor2')], default='Monitor2', max_length=10)),
                ('marca_monitor', models.CharField(default='Dell', max_length=10)),
                ('modelo', models.CharField(default='E1916', max_length=30)),
                ('service_tag', models.CharField(max_length=30)),
                ('polegadas', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Monitor',
            },
        ),
    ]
