# Generated by Django 4.1.1 on 2022-09-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='marca_monitor2',
            field=models.CharField(default='Dell', max_length=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='modelo2',
            field=models.CharField(default='E1916', max_length=30),
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor2',
            field=models.CharField(choices=[('Monitor1', 'Monitor1'), ('Monitor2', 'Monitor2')], default='Monitor2', max_length=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='polegadas2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='service_tag2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor',
            field=models.CharField(choices=[('Monitor1', 'Monitor1'), ('Monitor2', 'Monitor2')], default='Monitor1', max_length=10),
        ),
    ]
