# Generated by Django 4.1.1 on 2022-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PCP', 'DESKTOP'), ('NOT', 'NOTEBOOK')], default='PCP', max_length=3)),
                ('nome_pc', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('processador', models.CharField(max_length=20)),
                ('ano_compra', models.CharField(max_length=5)),
                ('service_tag', models.CharField(max_length=15)),
                ('memoria_ram', models.CharField(max_length=10)),
                ('armazenamento', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('DSP', 'DISPONÍVEL'), ('OCP', 'OCUPADO')], default='DSP', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Maquina',
            },
        ),
    ]
