# Generated by Django 4.1.1 on 2022-09-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='status',
            field=models.CharField(choices=[('DSP', 'Disponivel'), ('OCP', 'Ocupado')], default='Disponivel', max_length=15),
        ),
    ]
